server:
  port: 8000

spring:
  application:
    name: api
  cloud:
    gateway:
      routes:
        - id: feed-fetcher
          uri: lb://feed-fetcher
          predicates:
            - Path=/feed-fetcher/**
        - id: core
          uri: lb://core
          predicates:
            - Path=/core/**
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
